apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mycloud-qa
resources:
  - ../../base
labels:
  - pairs: { env: qa }
images:
  - name: mycloud-api
    newName: ghcr.io/moheddine-belhaj/mycloud-api
    newTag: sha-REPLACEME