apiVersion: v1
data:
    SESSION_SECRET: ENC[AES256_GCM,data:Zf70qH/2rhWQj07YK7rU+PzGLi8P7LQmoRcim/ZbSRJ1KedNBL2Yp4LTU+oEpeij0EjzFZy7n4rOpf+t,iv:MySzx0JK02Dzu0qBUuXWWjwcpxhZIIx+FPA43rKqjdw=,tag:jyVoWvFtDL8ZuvmDT8SesA==,type:str]
kind: Secret
metadata:
    name: api-secrets
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1eVBWZGJkYXYvb0gvN1hQ
            UEJxSWN2eGVlcXdjOVhwbWQ4UnRyUEJGMGdNCkQ0aTNnQlQxK1Y0NFk3RTRkQzRm
            SW9OZzlPQ1BCYlVQMXlxNitVRnFmOFEKLS0tIHdDQW9jZzJiekhKOExjby9OMk04
            a0hScE1HMWFuaU1tTDJKeGw0bGlNQVUKoUa66dHaJdOdCEKqBiaGFgWsVZSe1u75
            mZtT40jkD0PW59U/HkwGw7BwtZ6ITrvklZQvb1DNvmfT8b7R0IoDHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ndesspjm65cthkgjvktfmuhnpw53k78d520e32yg6wvd9x90ws2qdvryks
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T16:54:27Z"
    mac: ENC[AES256_GCM,data:sorFxrgrhcllFquqpkeelN5sy+3PjyeljlauMYuMfPUsXUe4L66uqs/j9gTAWemlJwmGBTl04UzdRxtQvPPqY/58Wvv6i+Qi2FsY3KNHBCteECB1RRFbKSCrF+fNq2cBv0ZFqlknpqWfM+aAPz0Z0Hop3+mB7buOj5mvtQoKiLw=,iv:FtquTCowV51fhoDuKtQhto/MbuHKgTFZ7rndU4s/P0E=,tag:4LzfaHNwBzJHCVSeipoxXQ==,type:str]
    version: 3.13.3
