apiVersion: v1
data:
    SESSION_SECRET: ENC[AES256_GCM,data:I546OVx07bdT54zxV2sO6OA/arxjCXtCyADyh4kjErun9+297rBa8PScbjHgradhrFEp7KFWY4cvFHpE,iv:r0ECctJxXu6wJ4IKHtbv8k/ykX2qMxoMEZ/OFosDYPc=,tag:D3aMmidJSCOpCpqE/vyFYA==,type:str]
kind: Secret
metadata:
    name: api-secrets
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZmJVcVU4L29FZS9iZmhk
            L0o2UHF0QTBXNHNZR0EweFpWYTRaVlB4NnlNClNXSVlUNUlIYitvbTJYTVBDZUcy
            OHk1SU1zYVVxRFBZajNaN2EvNWxaMTgKLS0tIEVWZEZDU01iOGlBcmNWM0dFTllG
            MEVDcTVNMk5EUmp4MkpOc2dwTWhtNjAKJLSjdWWWJ1617/tvyi7351ptlTBMS11d
            SMC4h6E9E6kN4D/NiF2NpwkUtyHO0UaPjkXf++Qp0Ldz8AvgdZwDQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ndesspjm65cthkgjvktfmuhnpw53k78d520e32yg6wvd9x90ws2qdvryks
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T16:54:27Z"
    mac: ENC[AES256_GCM,data:4L/UfiRv0cTZpFvBmVS8AwRCR1ijWzSCwgjs8t/qar3F4ykVcjgbRKHjEVduVRxRz3fZyjulOqOGAa7ycqRL0UOE4XjsaqR1UG3EFJNQNgZMpNLlIACAVggXHrHVn5MEGIv9Z4SIaRW06PgHQQeUJ3atvcCIvnUt4hLt1vpVJPw=,iv:m6SR6wNu9ZpSF7zZt67XVwgBEkQPoJXM1q7CQJ9k42o=,tag:L5vsGQm3d9VYzUJuh/oqNg==,type:str]
    version: 3.13.3
