apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mycloud-dev
resources:
- ../../base
labels:
- pairs:
    env: dev
images:
- name: mycloud-api
  newName: ghcr.io/moheddine-belhaj/mycloud-api
  newTag: sha-58fc018
generators:
  - secret-generator.yaml
