apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mycloud
resources:
  - ../../base
# newTag is rewritten by the "deploy" job in .github/workflows/backend.yml on every push to main.
images:
  - name: mycloud-api
    newName: ghcr.io/moheddine-belhaj/mycloud-api
    newTag: latest
