apiVersion: v1
data:
    SESSION_SECRET: ENC[AES256_GCM,data:bRuoc+YOOKnHvSwkLH5Q2uKjdMaqK9tbIY1ueMwIpMiVIFuf4qZ1ac2VPi6dhhWsquOrWu71+78dmzzH,iv:8cnKLnN+H1lSU0qWfDZ3hesHMMEFTpv4/61kQ1iAWBY=,tag:ODmKVKr1FVyYODIy18G1KA==,type:str]
kind: Secret
metadata:
    name: api-secrets
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RldEMWpOVjhaZ0x3bkhY
            SkZ0ZU8zdnpoWlo2K3cyZlYva3BOUk1WckJvCllFZHlyL3IxRTBlcnZ3UG4xK1BO
            NlRLZG53TllYM1l3MDZLeFdmeUlvOGsKLS0tIGpIbGprQ1F0TXlCcTZRenByMWRk
            MS8zODF0YXJxRFhJUVNJYjJueDFXbHcKVERJkiIWe2tohHld2kU1J8SJZSuU6o4m
            G9hgqDDhcW0ZgPFOeiVtQ//rjmRNB9lsKEBbkYlMEWODttR2oWd3VA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ndesspjm65cthkgjvktfmuhnpw53k78d520e32yg6wvd9x90ws2qdvryks
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T16:54:27Z"
    mac: ENC[AES256_GCM,data:4ce2UHiVsJf4yhOpJ/rBEcBQL6SDBxALcfePTcCYz4YxSDEDj7C+4KfFylTij/62w72O1R/AlvbQkY3NV3YDGU3oq/8yEGKd7wMcXNJSBS8Xyfq9EIH7UJNYYo6DUoe5BzyOWKt2ZXgzU3TLgEoFSNbUc+XYKLdSroPSPogPlBc=,iv:dp6l/7FUabEpRMQCg/WooGvdsWjycmbZ5wWWr42o0jg=,tag:vq1jZBjQ6Or/ptyrx38oKw==,type:str]
    version: 3.13.3
