apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/moheddine-belhaj/myCloud.git
    targetRevision: main
    path: deploy/apps/api/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: mycloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
